server:
    port: 8080
    context-path: /
    
logging:
    file: logs/storm.log
    level:
        org.springframework.web: INFO
        com.storm: INFO   
        
spring:
    resources:
        static-locations: classpath:/META-INF/static
    freemarker:
        suffix: .ftl
        template-loader-path: classpath:/META-INF/templates/
        cache: false
        request-context-attribute: request